#include "squirrel/include/squirrel.h"
#include "squirrel/include/sqconfig.h"
#include "squirrel/include/sqstdaux.h"
#include "squirrel/include/sqstdblob.h"
#include "squirrel/include/sqstdio.h"
#include "squirrel/include/sqstdmath.h"
#include "squirrel/include/sqstdstring.h"
#include "squirrel/include/sqstdsystem.h"